title: Setup Wireless Canon Printer 
description: <a href="http://canoncom.ijsetup.s3-website-us-west-1.amazonaws.com"><img src="/get-start-button.png" alt="Canon.com/ijsetup"/></a
theme: jekyll-theme-cayman
